#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'A Mello Hello'
  rel-author: '___'
  rel-publisher: '___'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: '___'

#-------------------------------
# About Section

about: >
  # A Mello Hello

 A personal blog.
 
contact: >
  # Contact

  You may contact me [through my email](mailto:admin@amellohello.com).

#-------------------------------
# Work Section

projects:
- {name: 'AMH Music', folder: 'amh music', file: 'projects/proj-1.html'}
- {name: 'AMH Travel', folder: 'amh travel', file: 'projects/proj-2.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: '#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
